baseURL = "https://youth-cornelia.github.io/"
title = "My Blog"
theme = "hugo-theme-stack"
languageCode = "en-us"
defaultContentLanguage = "en"
[pagination]
pagerSize = 10

[params.author]
name = "Youth Cornelia"
bio = "Computer Science 路 Projects 路 Notes"

[params.sidebar]
subtitle = "Computer Science 路 Projects 路 Notes"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[params.footer]
since = 2024
custom = true
customText = "YOUTH"

[params.article]
toc = true

[params.widgets]
homepage = ["search", "archives", "tag-cloud"]
page = ["toc", "search", "archives", "tag-cloud"]

[params]
mainSections = ["post"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 4

[params.colorScheme]
toggle = true      
default = "auto" 

